pull_request_rules:
  - name: automatic merge for Greenkeeper pull requests
    conditions:
      - author=greenkeeper[bot]
      - status-success=greenkeeper/verify
    actions:
      merge:
        method: merge
