pull_request_rules:
  - name: automatic merge for Greenkeeper pull requests
    conditions:
      - author=dependabot[bot]
      - status-success=security/snyk (palashmon)
    actions:
      merge:
        method: merge
