name: Auto-approve PR
on: pull_request_target
permissions:
  contents: write
  pull-requests: write
jobs:
  auto-approve-renovate-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@1d96c772d19495a3b5c517cd2bc0cb401ea0529f # v4.1.3
        with:
          fetch-depth: '0'
      - name: Approve PR
        if: github.actor == 'renovate[bot]'
        run: |
          gh pr review --approve ${{ github.event.number }} -b "I'm **approving** \
          this pull request because it includes a patch or minor update."
        env:
          GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}"