name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request: # PRs to main branches
  workflow_dispatch: # manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  test:
    uses: palashmon/reusable-workflows/.github/workflows/main-build.yml@main
